---
name: mostly-harmless
path: /opt/mostly-harmless

user: fprefect
group: fprefect

splunk: []
#   - log_path: None
#     index: None
#     sourcetype: None
#     source: None

# App configurable settings for the SplunkForwarder
# splunk_conf:
#   # `limits.conf`
#   limits:
#     ghoti: 'coo-coo'
