---
# APP - Application Specific Settings
# ===================================

# Application Name
# ----------------
# The name of the application. This name should match here, the name of the TAC
# repo and the name of the application in Harness.
name: mostly-harmless

# Application Path
# ----------------
# The path where you would like the application installed. This is the path to
# which the application artifact will be un-archived and from which it will be
# run.
path: /opt/mostly-harmless

# Artifact Options
# ----------------
# Options that effect the artifact installation.
#
# :expand: Whether or not to expand the artifact. By default Tsunami will expand
#          all artifact formats except ``JAR`` and ``WAR``. You can use this
#          flag to override that behavior. | **Optional**
# artifact:
#   expand: yes | no

# Application User & Group Ownership
# ----------------------------------
# The user and group that should own and run the application.
user: fprefect
group: fprefect

# Splunk Log Files
# ----------------
# .. _sourcetype: https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/Listofpretrainedsourcetypes
#
# Log files that should be sent to Splunk. You can specify multiple log files,
# each using the following settings:
#
# :log_path: The path to the actual log | **Required**
# :index: The Splunk index to send the log to | **Required**
# :source: Sub-grouping for the log file | **Optional**
# :`sourcetype`_: The type of log file | **Required**
#
splunk:
  - log_path: "/opt/mostly-harmless/logs/request.log"
    index: "devops_{{ 'prod' if env == 'prod' else 'nonprod' }}_logs"
    sourcetype: generic_single_line
    source: "mostly-harmless-app-requests-{{ env }}"
  - log_path: "/var/log/nginx/access.log"
    index: "devops_{{ 'prod' if env == 'prod' else 'nonprod' }}_logs"
    sourcetype: generic_single_line
    source: "mostly-harmless-nginx-access-{{ env }}"
#
# SplunkForwarder Configuration
# -----------------------------
# .. _thruput/maxKBps: https://docs.splunk.com/Documentation/Splunk/8.2.5/Admin/Limitsconf#.5Bthruput.5D
#
# App configurable settings for the SplunkForwarder
#
# We currently only support tweaking the following setting in ``limits.conf``.
#
# :`thruput/maxKBps`_: The maximum speed that incoming data is processed
## splunk_conf:
##   limits:
##     thruput:
##       maxKBps: 1024
