---
# The name of the application.
name: mostly-harmless

# The installation path
path: /opt/mostly-harmless

# The user and group that should own and run the application
user: fprefect
group: fprefect

# Log files that should be sent to Splunk.
# Requires three settings per log file.
# 1. log_path - The path to the actual log. Required.
# 2. index - The Splunk index to send the log to. Required.
# 3. source - Subgrouping for the log file. Optional.
# 4. sourcetype - The type of log file. Required.
#        - See https://docs.splunk.com/Documentation/Splunk/8.0.5/Data/Listofpretrainedsourcetypes
splunk:
  - log_path: "/opt/mostly-harmless/logs/request.log"
    index: devops_nonprod_logs
    sourcetype: generic_single_line
    source: mostly-harmless-app-requests-dev
  - log_path: "/var/log/nginx/access.log"
    index: devops_nonprod_logs
    sourcetype: generic_single_line
    source: mostly-harmless-nginx-access-dev

# App configurable settings for the SplunkForwarder
# splunk_conf:
#   # `limits.conf`
#   limits:
#     thruput:
#       maxKBps: 1024
