---
SHARED:
  params: {}

FILES:
  - name: mostly-harmless.conf
    metadata:
      path: /etc/nginx/conf.d
    params:
      port: 8080
  - name: server.json
    metadata:
      path: /opt/mostly-harmless/conf
    params:
      port: 4242
  - name: mostly-harmless.service
    metadata:
      path: /etc/systemd/system
