---
SHARED:
  params: {}

FILES:
  - name: mostly-harmless.conf
    metadata:
      path: /etc/nginx/conf.d
    params:
      port: 8080
  - name: index.html
    metadata:
      path: /opt/mostly-harmless/html
      owner: fprefect
      group: fprefect
      mode: 0644
