---

- name: Ensure Dest Dirs Exist
  file:
    path: "{{ base_path }}/{{ item }}"
    state: directory
  loop:
    - html
    - html/images

- name: Copy Files
  copy:
    src: "{{ item.file }}"
    dest: "{{ base_path }}/{{ item.dir }}/{{ item.file }}"
    mode: "0644"
  loop:
    - { file: "mostly-harmless-dev.jpg",     dir: "html/images" }
    - { file: "mostly-harmless-qa.jpg",      dir: "html/images" }
    - { file: "mostly-harmless-default.jpg", dir: "html/images" }

- name: Install index.html
  template:
    src: index.html.j2
    dest: "{{ base_path }}/html/index.html"
    mode: "0644"
