---

- name: Ensure Dest Dirs Exist
  file:
    path: "{{ base_path }}/{{ item }}"
    state: directory
  loop:
    - html
    - html/images

- name: Copy Splash Image
  copy:
    src: "mostly-harmless-{{ env }}.jpg"
    dest: "{{ base_path }}/html/images/mostly-harmless-{{ env }}.jpg"
    mode: "0644"

- name: Install index.html
  template:
    src: index.html.j2
    dest: "{{ base_path }}/html/index.html"
    mode: "0644"
